### PR TITLE
added webbook log for the Ai doctor 

### PR DESCRIPTION
**Pull request by James-the-Coding-Gamer**
added webbook log for the Ai doctor so people can keep track of the abusers in RP servers

### CODE REVIEW

**Comment by James-the-Coding-Gamer** [comment]
I know i needed it so thought others might need it as well

**Comment by RealStonerGamer** [comment]
that should do it

**Comment by James-the-Coding-Gamer** [comment]
ok now i am done  not sure why i was setting the config call that way lol

**Comment by James-the-Coding-Gamer** [comment]
@BurntJannings  feel free to use if you like if not you can close the PR

**Comment by James-the-Coding-Gamer** [comment]
image

**Comment by BurntJannings** [comment]
Default Webhook addition is in and added and working, client side additions are up to the clients

**Pull request closed without merging**
